### ISSUE TITLE
update dependency to frege-native-gen

### ISSUE THREAD

**Issue by Dierk** [Frege/frege-gradle-plugin#11]
frege-native-gen:1.0-SNAPSHOT is no longer available

**Comment by mperry** [comment]
@Dierk I stuffed up the initial release, building it in Java 8, instead of Java 7.  This manifest when compiling using Java 7 and the Frege compiler uses the internal Java compiler which does not understand Java 8.  So I am hoping this weekend to patch the releases for the plugin, interpreter, repl and native gen.

**Comment by Dierk** [comment]
I also did some work last night but forgot to update this issue. I made a "jitpack" release by just tagging this repo with "release-3.0". So easy!

**Comment by mperry** [comment]
@Dierk I saw someone mention Jitpack last night, it might have been you.  I will have to look into it.
